import {
  pgTable,
  serial,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
  decimal,
  date,
} from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 150 }).notNull(),
  email: varchar('email', { length: 300 }).notNull().unique(),
  emailVerified: timestamp('email_verified'),
  passwordHash: varchar('password_hash', { length: 500 }),
  avatarUrl: varchar('avatar_url', { length: 500 }),
  role: varchar('role', { length: 20 }).default('user'),
  bio: text('bio'),
  reviewCount: integer('review_count').default(0),
  createdAt: timestamp('created_at').defaultNow(),
});

export const categories = pgTable('categories', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 100 }).notNull(),
  slug: varchar('slug', { length: 100 }).notNull().unique(),
  icon: varchar('icon', { length: 50 }),
  color: varchar('color', { length: 20 }),
  description: text('description'),
  itemCount: integer('item_count').default(0),
  createdAt: timestamp('created_at').defaultNow(),
});

export const items = pgTable('items', {
  id: serial('id').primaryKey(),
  slug: varchar('slug', { length: 200 }).notNull().unique(),
  name: varchar('name', { length: 200 }).notNull(),
  nameAr: varchar('name_ar', { length: 200 }),
  categoryId: integer('category_id').references(() => categories.id),
  description: text('description').notNull(),
  descriptionAr: text('description_ar'),
  imageUrl: varchar('image_url', { length: 500 }),
  imageAlt: varchar('image_alt', { length: 200 }),
  governorate: varchar('governorate', { length: 100 }),
  area: varchar('area', { length: 100 }),
  address: text('address'),
  latitude: decimal('latitude', { precision: 10, scale: 7 }),
  longitude: decimal('longitude', { precision: 10, scale: 7 }),
  googleMapsUrl: varchar('google_maps_url', { length: 500 }),
  priceMin: integer('price_min'),
  priceMax: integer('price_max'),
  priceLabel: varchar('price_label', { length: 50 }),
  priceCurrency: varchar('price_currency', { length: 5 }).default('EGP'),
  website: varchar('website', { length: 300 }),
  instagram: varchar('instagram', { length: 150 }),
  phone: varchar('phone', { length: 30 }),
  tags: text('tags').array(),
  isVerified: boolean('is_verified').default(false),
  isFeatured: boolean('is_featured').default(false),
  isActive: boolean('is_active').default(true),
  avgRating: decimal('avg_rating', { precision: 3, scale: 2 }).default('0.00'),
  totalReviews: integer('total_reviews').default(0),
  submittedBy: integer('submitted_by').references(() => users.id),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const reviews = pgTable('reviews', {
  id: serial('id').primaryKey(),
  itemId: integer('item_id').references(() => items.id).notNull(),
  userId: integer('user_id').references(() => users.id).notNull(),
  rating: integer('rating').notNull(),
  title: varchar('title', { length: 200 }),
  body: text('body').notNull(),
  pros: text('pros'),
  cons: text('cons'),
  visitedAt: date('visited_at'),
  status: varchar('status', { length: 20 }).default('pending'),
  autoApproved: boolean('auto_approved').default(false),
  adminNote: text('admin_note'),
  helpfulCount: integer('helpful_count').default(0),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const adminSettings = pgTable('admin_settings', {
  id: serial('id').primaryKey(),
  key: varchar('key', { length: 100 }).notNull().unique(),
  value: text('value').notNull(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
